name: e_comerce
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  passwordfield: ^0.0.82
  font_awesome_flutter: ^9.0.0
  splashscreen: ^1.3.5
  pin_code_fields: ^7.0.0
  bottom_navy_bar: ^6.0.0
  http: ^0.12.2
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  awesome_dialog: ^1.3.2
  lite_rolling_switch: ^0.1.1
  flutter_dropdown: ^0.0.8
  easy_localization: ^3.0.0
  data_connection_checker: ^0.3.4
  url_launcher: ^6.0.3
<<<<<<< HEAD
  intl_phone_field: ^2.0.0
  rflutter_alert: ^2.0.2
=======
  firebase_core:
  #firebase_messaging: ^7.0.3
  firebase_messaging: ^9.1.3
  firebase_analytics:
  flutter_local_notifications:
  get_it: ^5.0.1
>>>>>>> 83e0e1b8e3f738bd110950e0d5bd777658981362

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true


  assets:
   - assets/images/
   - assets/translations/


